FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3.9 \
    python3-pip

RUN python3 -m pip install ngrok

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip setuptools
RUN pip install --no-cache-dir -r requirements.txt
RUN chmod 755 .

COPY . .