name: testing_CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3      
      - run: docker-compose -f docker-compose.yml build
      - run: docker-compose -f docker-compose.yml up -d
      - run: sleep 5
      - run: docker-compose down

  deploy:
    runs-on: ubuntu-latest
    - name: ssh key passphrase
    uses: appleboy/ssh-action@v1
    with:
      host: ${{ secrets.SSH_HOST }}
      username: ${{ secrets.SSH_USERNAME }}
      key: ${{ secrets.SSH_KEY }}
      port: ${{ secrets.SSH_PORT }}
      script: |
        whoami
        ls -al
