name: testing_CI

on: [push]

jobs:
  test_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: docker-compose -f docker-compose.yml build
      - run: docker-compose -f docker-compose.yml up -d
      - run: sleep 5
      - run: docker-compose down
